pipeline {
    agent {
        docker {
            image 'openjdk:17-jdk-alpine'
            args '--user root'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                sh 'echo passed'
            }
        }
        stage('Build and Test') {
            steps {
                // List files for verification
                sh 'ls -ltr'

                // Build the project and create a JAR file
                sh '''
                    cd CI-CD
                    mvn clean package
                '''
            }
        }
    }
}
