pipeline {
    agent {
        docker {
            image 'maven:3.8.5-openjdk-17-slim'
            args '--user root'
        }
    }
    stages {
        stage('Cleanup Workspace') {
            steps {
                deleteDir() // This will clean the workspace before each build
            }
        }
        stage('Checkout') {
            steps {
                sh 'echo passed'
            }
        }
        stage('Build and Test') {
            steps {
                // List files for verification
                sh 'ls -ltr'

                // Build the project and create a JAR file
                sh '''
                    cd CI-CD
                    mvn clean package
                '''
            }
        }
        stage('static code analysis'){
            environment {
                SONAR_URL = "http://13.233.227.174:9000"
      }
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh 'cd CI-CD && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        }
      }
        }
    }
}
